# Video settings
VIDEO_WIDTH = 320
VIDEO_HEIGHT = 240
COMPOSITE_WIDTH = 640
COMPOSITE_HEIGHT = 480
WEBCAM_ID = 0

# WebRTC settings
WEBRTC_HOST = "0.0.0.0"
WEBRTC_PORT = 9999

# Frame buffer settings
FRAME_BUFFER_SIZE = 2